services:
  - type: web
    name: dog-rating-api
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dogratings
          property: connectionString

databases:
  - name: dogratings
